### ISSUE TITLE
getting started Documentation seems to be off after webpage move

### ISSUE THREAD

**Issue by leifskje** [kantega/Flyt-cms#1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project openaksess: The desired archetype does not exist (no.kantega.archetypes:aksess-project:latest) -> [Help 1]

JDK 8 77
Maven 3.3.9
Attached cmd output with and without -X

[Flyt error basic first.txt](https://github.com/kantega/Flyt-cms/files/240076/Flyt.error.basic.first.txt)
[Flyt error full first.txt](https://github.com/kantega/Flyt-cms/files/240095/Flyt.error.full.first.txt)

Tried instaling some plugins, and some tweeks with no prevail.

**Comment by computerlove** [comment]
Kommandoen var feil har endre til 

mvn archetype:generate -DarchetypeGroupId=org.kantega.archetypes -DarchetypeArtifactId=openaksess-project -DarchetypeVersion=LATEST -DarchetypeRepository=http://opensource.kantega.no/nexus/content/groups/public
